apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: leui/tcc-backend:8104fb7bf980d809b3e85c68b78a50a38c71fdb2
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-env
                  key: db_user
            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: backend-env
                  key: db_pass
            - name: SECRET
              valueFrom:
                configMapKeyRef:
                  name: backend-env
                  key: secret
            - name: REFRESH_SECRET
              valueFrom:
                configMapKeyRef:
                  name: backend-env
                  key: refresh_secret
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-env
                  key: port
            - name: ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: backend-env
                  key: origin
            - name: CERT_PATH
              value: "/etc/certs/global-bundle.pem"
          volumeMounts:
            - name: documentdb-cert
              mountPath: "/etc/certs"
              readOnly: true
      volumes:
        - name: documentdb-cert
          configMap:
            name: documentdb-cert
      nodeSelector:
        app: backend
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: backend
