apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: leui/tcc-backend:1def740b5b1b9523bcbc698451295d5b31127f73
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: backend-env
                  key: db_user
            - name: DB_PASS
              valueFrom:
                configMapKeyRef:
                  name: backend-env
                  key: db_pass
            - name: SECRET
              valueFrom:
                configMapKeyRef:
                  name: backend-env
                  key: secret
            - name: REFRESH_SECRET
              valueFrom:
                configMapKeyRef:
                  name: backend-env
                  key: refresh_secret
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: backend-env
                  key: port
            - name: ORIGIN
              valueFrom:
                configMapKeyRef:
                  name: backend-env
                  key: origin
      nodeSelector:
        app: backend
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: backend
