apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- backend-deployment.yaml
- backend-service.yaml
namespace: backend
images:
- name: backend
  newName: leui/tcc-backend
  newTag: 0db77bae8e61948cdbfb6da54446133e64ea9d7d
