const eletivas = {
  period: "Atividades Acadêmicas Optativas",
  subjects: [
    {
      codigo: "COE471",
      nome: "Sensores e Atuadores",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 75,
    },
    {
      codigo: "COE714",
      nome: "Filtros Digitais",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "COE715",
      nome: "Eletrônica de Potência I",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "COE717",
      nome: "Programação Concorrente",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "COE718",
      nome: "Processamento Adaptativo de Sinais",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "COE719",
      nome: "Aplicações de Eletrônica de Potência",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "COE728",
      nome: "Redes de Computadores",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "COE729",
      nome: "Arquitetura e Protocolos de Redes",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "COE732",
      nome: "Sistemas Não Lineares I",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "COE736",
      nome: "Controle Digital",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "COE745",
      nome: "Matemática para Controle",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "COE746",
      nome: "Introdução à Robótica",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "COE768",
      nome: "Processamento de Sinais da Fala",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "COE775",
      nome: "Processamento de Sinais Aleatórios",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "COE776",
      nome: "Detecção e Estimação de Sinais",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "COE778",
      nome: "Sistemas Multitaxas e Wavelets",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "COE781",
      nome: "Compressão de Imagens",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "COE784",
      nome: "Processamento Digital de Imagens",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "COE793",
      nome: "Simulação de Conversão Estatística de Potência",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "COE798",
      nome: "Comunicações Móveis I",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "COE817",
      nome: "Distribuição de Conteúdo na Internet",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "COE828",
      nome: "Tópicos Especiais em Redes de Computadores",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "COE829",
      nome: "Tópicos Especiais em Protocolos de Comunicação",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE710",
      nome: "Redes Móveis",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE713",
      nome: "Aplicações de Microeletrônica em Eletrônica de Potência",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE716",
      nome: "Internet das Coisas",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE720",
      nome: "Compactação de Sinais",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE721",
      nome: "Redes Neurais Feedforward",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE722",
      nome: "Redes Neurais Não Supervisionadas",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE723",
      nome: "Otimização Natural",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE729",
      nome: "Segurança em Redes de Computadores",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE730",
      nome: "Inteligência de Enxame",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE739",
      nome: "Sistemas a Eventos Discretos",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE747",
      nome: "Diagnóstico de Falhas em Sistemas",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE759",
      nome: "Tópicos Especiais em Internet de Nova Geração",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE767",
      nome: "Computação em Redes Inteligentes",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE769",
      nome: "Redes Adaptativas e Aprendizado Multitarefa",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE772",
      nome: "Estimação Linear Ótima",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE782",
      nome: "Análise de Componentes Independentes",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE784",
      nome: "Tópicos Especiais em Redes e Segurança",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE786",
      nome: "Processamento de Imagens no Pipeline",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE794",
      nome: "Tópicos Especiais em Ferramentas de Análise de Sistemas Redundantes",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE796",
      nome: "Tópicos Especiais em Comunicações Móveis e Segurança",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE797",
      nome: "Tecnologia Sonar",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE825",
      nome: "Roteamento em Redes de Computadores",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE826",
      nome: "Tópicos Especiais em Comunicações Móveis e Segurança",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE846",
      nome: "Aplicações e Transporte de Redes de Computadores",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "CPE847",
      nome: "Programação Orientada a Objetos para Redes de Computadores",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 45,
    },
    {
      codigo: "EEL418",
      nome: "Programação Avançada",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 75,
    },
    {
      codigo: "EEL472",
      nome: "Síntese Moderna de Circuitos",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL485",
      nome: "Software I",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL606",
      nome: "Optoeletrônica",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL811",
      nome: "Áudio",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL812",
      nome: "Circuitos de Potência",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL813",
      nome: "Circuitos Analógicos Integrados e Processamento de Sinais",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL814",
      nome: "Microeletrônica I",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL815",
      nome: "Microeletrônica II",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL816",
      nome: "Processamento de Voz",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "10.0",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL817",
      nome: "Redes Neurais",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL818",
      nome: "Arquitetura para Processamento Digital de Sinais",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL819",
      nome: "Imagens Médicas",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL820",
      nome: "Tópicos Especiais em Circuitos e Instrumentação",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL831",
      nome: "Antenas e Propagação",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL832",
      nome: "Circuitos de Comunicações",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL833",
      nome: "Microondas",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL834",
      nome: "Processamento Digital de Imagens",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL835",
      nome: "Sistemas de Comunicações",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL836",
      nome: "Telefonia",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL837",
      nome: "Televisão Analógica",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL838",
      nome: "Televisão Digital",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL839",
      nome: "Transmissão Digital",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "8.5",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL840",
      nome: "Tópicos Especiais em Sistemas de Comunicações",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL841",
      nome: "Novas Mídias",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "8.3",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL850",
      nome: "Software Livre e Metodologias Participativas",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL851",
      nome: "Controle de Processos para Computadores",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 75,
    },
    {
      codigo: "EEL852",
      nome: "Controle Multivariável",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL853",
      nome: "Controle Ótimo",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL854",
      nome: "Identificação de Sistemas e Controle Adaptativo",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL855",
      nome: "Robótica e Automação",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL856",
      nome: "Sistemas de Controle Não Lineares",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL857",
      nome: "Otimização em Grafos",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL858",
      nome: "Otimização Linear e Não Linear",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL859",
      nome: "Introdução à Programação Linear",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL860",
      nome: "Tópicos Especiais em Sistemas de Controle",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL871",
      nome: "Banco de Dados",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "7.0",
      status: "",
      cargaHor: 75,
    },
    {
      codigo: "EEL872",
      nome: "Computação Paralela e Distribuída",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL873",
      nome: "Engenharia de Software",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 75,
    },
    {
      codigo: "EEL874",
      nome: "Inteligência Artificial",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "9.0",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL875",
      nome: "Internet e Arquitetura TCP/IP",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 75,
    },
    {
      codigo: "EEL876",
      nome: "Microcomputadores",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL877",
      nome: "Modelagem e Avaliação de Desempenho de Redes",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL878",
      nome: "Redes de Computadores I",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "7.2",
      status: "",
      cargaHor: 75,
    },
    {
      codigo: "EEL879",
      nome: "Redes de Computadores II",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "7.5",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL880",
      nome: "Tópicos Especiais em Sistemas Digitais",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL881",
      nome: "Teoria da Computação",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL882",
      nome: "Computação Gráfica",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 75,
    },
    {
      codigo: "EEL883",
      nome: "Interface e Integração de Sistemas",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL884",
      nome: "Engenharia de Software Orientada a Objetos",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL885",
      nome: "Big Data",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL892",
      nome: "Internet de Nova Geração e Segurança de Redes",
      ementa: "",
      credito: 5.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 55,
    },
    {
      codigo: "EEL911",
      nome: "Teoria dos Jogos Aplicada à Tecnologia da Informação",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL912",
      nome: "Processamento de Sinais de Áudio",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL913",
      nome: "Software para Smartphone",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL970",
      nome: "Software para Smartphones",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEW016",
      nome: "Capacitação em Normalização",
      ementa: "",
      credito: 2.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 30,
    },
    {
      codigo: "EEW018",
      nome: "Fundamentos de Metrologia e Avaliação da Conformidade",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEW515",
      nome: "Tópicos Especiais em Engenharia",
      ementa: "",
      credito: 2.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 30,
    },
    {
      codigo: "FIS352",
      nome: "Física de Materiais e Dispositivos Semicondutores",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "FIW487",
      nome: "Tópicos em Física Contemporânea II",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
  ],
};

module.exports = eletivas;
