const humanas = {
  period: "Atividades Acadêmicas Optativas (Escolha Restrita)",
  subjects: [
    {
      codigo: "EEI202",
      nome: "Humanidades e Ciencias Sociais",
      ementa: "",
      credito: 2.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 30,
    },
    {
      codigo: "EEI206",
      nome: "Historia da Tecnologia",
      ementa: "",
      credito: 2.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 30,
    },
    {
      codigo: "EEI426",
      nome: "Engenharia do Trabalho",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "EEI625",
      nome: "Gestão de Projetos Solidários",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 45,
    },
    {
      codigo: "EEL191",
      nome: "Engenharia e Sociedade",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "EEL192",
      nome: "Evolucao da Ciencia",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "EEL193",
      nome: "O Trabalho do Futuro",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "EEL212",
      nome: "Metodologia da Pesquisa",
      ementa: "",
      credito: 2.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 30,
    },
    {
      codigo: "EET100",
      nome: "Tecnologia e Desenv Social",
      ementa: "",
      credito: 2.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 30,
    },
    {
      codigo: "EEW215",
      nome: "Tóp Esp História da Engenharia",
      ementa: "",
      credito: 2.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 30,
    },
    {
      codigo: "EEW601",
      nome: "Analise e Producao Textual",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 90,
    },
    {
      codigo: "EEW602",
      nome: "Evolucão Ciência e Engenharia",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "EQE040",
      nome: "Introd Metodologia Científica",
      ementa: "",
      credito: 2.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 30,
    },
    {
      codigo: "FCA218",
      nome: "Antropologia Cultural",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "FCB618",
      nome: "Sociedade e Direito",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "FCF108",
      nome: "Ética I",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "FCF243",
      nome: "Filosofia da Ciencia I EE",
      ementa: "",
      credito: 2.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 30,
    },
    {
      codigo: "FCF245",
      nome: "Filosofia da Natureza I EE",
      ementa: "",
      credito: 2.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 30,
    },
    {
      codigo: "FCF354",
      nome: "Epist e Hist das Ciencias I EE",
      ementa: "",
      credito: 2.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 30,
    },
    {
      codigo: "FCF362",
      nome: " Estética I",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "FCF654",
      nome: "Hist da Filos no Brasil I",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "FCP104",
      nome: "Introdução à Ciência Política",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "FCP645",
      nome: "Instituicoes Polit Brasileiras",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "FCP670",
      nome: "Crises da Realidade Brasileira",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "IHI056",
      nome: "Historiografia Brasileira II",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "IHI098",
      nome: "Movimento Operário no Brasil",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "IHI101",
      nome: "História Social da Arte I",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "IHI106",
      nome: "Top Esp em Hist do Brasil III",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "IHI143",
      nome: "Top Esp em Historia Moderna II",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "IBE599",
      nome: "Estudos da Lingua Brasileira de Sinais I",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "PRU110",
      nome: "Ciências Soc Gestão Pública I",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "PRU111",
      nome: "Teorias do Planejamento",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "PRU231",
      nome: "Formação Econ Soc Brasileira",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "EEW002",
      nome: "Sociedade de Debates I",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 30,
    },
    {
      codigo: "EEW003",
      nome: "Sociedade de Debates II",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 30,
    },
    {
      codigo: "EEWK01",
      nome: "Iniciação Científica I",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 180,
    },
    {
      codigo: "EEWK02",
      nome: "Iniciação Científica II",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 180,
    },
    {
      codigo: "EEWK03",
      nome: "Iniciação Científica III",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 180,
    },
    {
      codigo: "EEWU21",
      nome: "Estágio Não-obrigatório I",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 180,
    },
    {
      codigo: "EEWU22",
      nome: "Estágio Não-obrigatório II",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 180,
    },
    {
      codigo: "EEWU23",
      nome: "Estágio Não-obrigatório III",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 90,
    },
    {
      codigo: "EEWX03",
      nome: "Participação em Eventos I",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 45,
    },
    {
      codigo: "EEWX04",
      nome: "Participação em Eventos II",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 45,
    },
    {
      codigo: "EEWX05",
      nome: "Participação em Eventos III",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 15,
    },
    {
      codigo: "EEWX06",
      nome: "Projeto Cultural I",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 180,
    },
    {
      codigo: "EEWX07",
      nome: "Projeto Cultural II",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 90,
    },
    {
      codigo: "EEWX08",
      nome: "Part em Atividade Cult I",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 90,
    },
    {
      codigo: "EEWX09",
      nome: "Part em Atividade Cult II",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "EEWX10",
      nome: "Part em Atividade Cult III",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 15,
    },
    {
      codigo: "EEWX11",
      nome: "Competição Esportiva I",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 500,
    },
    {
      codigo: "EEWX12",
      nome: "Partic em Atividade Esport I",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 45,
    },
    {
      codigo: "EEWX13",
      nome: "Partic em Atividade Esport II",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 45,
    },
    {
      codigo: "EEWX14",
      nome: "Partic em Atividade Esport III",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 15,
    },
    {
      codigo: "EEWX15",
      nome: "Grupo de Estudo I",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 120,
    },
    {
      codigo: "EEWX16",
      nome: "Grupo de Estudo II",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 90,
    },
    {
      codigo: "EEWX17",
      nome: "Grupo de Estudo III",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "EEWX21",
      nome: "Atividade de Intercâmbio I",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 45,
    },
    {
      codigo: "EEWX22",
      nome: "Atividade de Intercâmbio II",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 45,
    },
    {
      codigo: "EEWX23",
      nome: "Mesário Voluntário",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 45,
    },
    {
      codigo: "EEWX24",
      nome: "Atividade de Intercâmbio III",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 30,
    },
    {
      codigo: "EEWX31",
      nome: "Trabalhos Comunitários I",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 90,
    },
    {
      codigo: "EEWX32",
      nome: "Trabalhos Comunitários II",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 45,
    },
    {
      codigo: "EEWX33",
      nome: "Trabalhos Comunitários III",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 45,
    },
    {
      codigo: "EEWX34",
      nome: "Acessibilidade I",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 30,
    },
    {
      codigo: "EEWX35",
      nome: "Acessibilidade II",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 60,
    },
    {
      codigo: "EEWX36",
      nome: "Acessibilidade III",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 180,
    },
    {
      codigo: "EEWX37",
      nome: "Acessibilidade IV",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 180,
    },
    {
      codigo: "EEWX38",
      nome: "Acessibilidade V",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 180,
    },
    {
      codigo: "EEWX39",
      nome: "Acessibilidade VI",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 180,
    },
    {
      codigo: "EEWX40",
      nome: "Acessibilidade VII",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 45,
    },
    {
      codigo: "EEWX51",
      nome: "Adm de Empresas Júnior I",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 180,
    },
    {
      codigo: "EEWX52",
      nome: "Adm de Empresas Júnior II",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 180,
    },
    {
      codigo: "EEWX53",
      nome: "Adm de Empresas Júnior III",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 180,
    },
    {
      codigo: "EEWY01",
      nome: "Equipe de Competição I",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 180,
    },
    {
      codigo: "EEWY02",
      nome: "Equipe de Competição II",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 180,
    },
    {
      codigo: "EEWY03",
      nome: "Equipe de Competição III",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 180,
    },
    {
      codigo: "EEWY21",
      nome: "Monitoria I",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 270,
    },
    {
      codigo: "EEWY22",
      nome: "Monitoria II",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 180,
    },
    {
      codigo: "EEWY23",
      nome: "Monitoria III",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 180,
    },
    {
      codigo: "EEWY31",
      nome: "Viagens/visitas Técnicas I",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 15,
    },
    {
      codigo: "EEWY32",
      nome: "Viagens/visitas Técnicas II",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 45,
    },
    {
      codigo: "EEWZ58",
      nome: "Ativ Curricular Extensão - Eco",
      ementa: "",
      credito: 0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora2: {
          dia: "",
          inicio: "",
          fim: "",
        },
        hora3: {
          dia: "",
          inicio: "",
          fim: "",
        },
      },
      nota: "",
      status: "",
      tipo: "Atividades Acadêmicas Optativas (Escolha Restrita)",
      cargaHor: 400,
    },
  ],
};

module.exports = humanas;
