const period1 = {
  period: "1",
  subjects: [
    {
      codigo: "EEL170",
      nome: "Computação I",
      ementa:
        "A solução de problemas utilizando computadores. Algoritmos: linguagens para especificar algoritmos, estruturas de dados e controle, modularização, refinamento etapa por etapa. Algoritmos para a solução de problemas numéricos e não numéricos. Pascal: arquivos, alocação dinâmica de memória e orientação a objetos. Introdução à Informática: o hardware e o software de computadores, a apresentação de informações, as linguagens de programação, o tele-processamento e as redes locais. Os impactos da computação.",
      credito: 5.0,
      prof: "Fernanda",
      sala: "H209",
      preReq: "",
      hora: {
        hora1: { dia: "TER", inicio: "15:00", fim: "17:00" },
        hora2: { dia: "QUI", inicio: "15:00", fim: "17:00" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 90,
    },
    {
      codigo: "FIS111",
      nome: "Física Experimental I",
      ementa: "",
      credito: 1.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 30,
    },
    {
      codigo: "FIT112",
      nome: "Física I - a",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "5.7",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "IQG111",
      nome: "Química Ee",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "MAC118",
      nome: "Cálculo Difer e Integral I",
      ementa: "",
      credito: 6.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 90,
    },
  ],
};

module.exports = period1;
