const period7 = {
  period: "7",
  subjects: [
    {
      codigo: "EEL615",
      nome: "Eletrônica IV",
      ementa: "",
      credito: 5.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "7.8",
      status: "",
      tipo: "7",
      cargaHor: 90,
    },
    {
      codigo: "EEL711",
      nome: "Processamento de Sinais",
      ementa: "",
      credito: 5.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "7.9",
      status: "",
      tipo: "7",
      cargaHor: 75,
    },
    {
      codigo: "EEL740",
      nome: "Comunicações II",
      ementa: "",
      credito: 5.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "8.1",
      status: "",
      tipo: "7",
      cargaHor: 75,
    },
    {
      codigo: "EEL760",
      nome: "Controle Linear II-A",
      ementa: "",
      credito: 5.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "9.3",
      status: "",
      tipo: "7",
      cargaHor: 75,
    },
    {
      codigo: "EEL770",
      nome: "Sistemas Operacionais",
      ementa: "",
      credito: 5.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "6.7",
      status: "",
      tipo: "7",
      cargaHor: 75,
    },
    {
      codigo: "EELX00",
      nome: "Projeto Integrado",
      ementa: "",
      credito: 1.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "9.8",
      status: "",
      tipo: "7",
      cargaHor: 30,
    },
  ],
};

module.exports = period7;
