const period4 = {
  period: "4",
  subjects: [
    {
      codigo: "EEL315",
      nome: "Eletrônica I",
      ementa: "",
      credito: 3.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "EEL420",
      nome: "Circuitos Elétricos I",
      ementa: "",
      credito: 5.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 75,
    },
    {
      codigo: "EEL470",
      nome: "Algoritmos e Estrut.de Dados",
      ementa: "",
      credito: 5.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 75,
    },
    {
      codigo: "EEL480",
      nome: "Sistemas Digitais",
      ementa: "",
      credito: 5.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 90,
    },
    {
      codigo: "FIM240",
      nome: "Física IV - a",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "FIN241",
      nome: "Física Experimental IV",
      ementa: "",
      credito: 1.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 30,
    },
  ],
};

module.exports = period4;
