const period5 = {
  period: "5",
  subjects: [
    {
      codigo: "EEL410",
      nome: "Eletrônica II",
      ementa: "",
      credito: 5.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "9.3",
      status: "",
      tipo: "5",
      cargaHor: 90,
    },
    {
      codigo: "EEL525",
      nome: "Circuitos Elétricos II",
      ementa: "",
      credito: 5.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "8.4",
      status: "",
      tipo: "5",
      cargaHor: 75,
    },
    {
      codigo: "EEL535",
      nome: "Teoria Eletromagnética II",
      ementa: "",
      credito: 5.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "8.2",
      status: "",
      tipo: "5",
      cargaHor: 75,
    },
    {
      codigo: "EEL555",
      nome: "Sistemas Lineares II",
      ementa: "",
      credito: 5.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "9.5",
      status: "",
      tipo: "5",
      cargaHor: 75,
    },
    {
      codigo: "EEL580",
      nome: "Arquitetura de Computadores",
      ementa: "",
      credito: 5.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "8.0",
      status: "",
      tipo: "5",
      cargaHor: 75,
    },
  ],
};

module.exports = period5;
