const period8 = {
  period: "8",
  subjects: [
    {
      codigo: "EEE387",
      nome: "Conversão de Energia",
      ementa: "",
      credito: 5.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "7.8",
      status: "",
      tipo: "8",
      cargaHor: 75,
    },
    {
      codigo: "EEL710",
      nome: "Instrumentação e Técnicas de Medidas",
      ementa: "",
      credito: 5.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "6.0",
      status: "",
      tipo: "8",
      cargaHor: 75,
    },
    {
      codigo: "EEWX00",
      nome: "Projeto de Graduação",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      tipo: "8",
      cargaHor: 180,
    },
  ],
};

module.exports = period8;
