const period2 = {
  period: "2",
  subjects: [
    {
      codigo: "EEH210",
      nome: "Engenharia e Meio Ambiente",
      ementa: "",
      credito: 2.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 30,
    },
    {
      codigo: "EEL270",
      nome: "Computação II",
      ementa: "",
      credito: 5.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 90,
    },
    {
      codigo: "EEL280",
      nome: "Circuitos Lógicos",
      ementa: "",
      credito: 5.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 90,
    },
    {
      codigo: "FIS121",
      nome: "Física Experimental II",
      ementa: "",
      credito: 1.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 30,
    },
    {
      codigo: "FIT122",
      nome: "Física II - a",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "MAC128",
      nome: "Cálculo Difer e Integral II",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
    {
      codigo: "MAE125",
      nome: "Álgebra Linear II",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "",
      status: "",
      cargaHor: 60,
    },
  ],
};

module.exports = period2;
