const period6 = {
  period: "6",
  subjects: [
    {
      codigo: "EEL515",
      nome: "Eletrônica III",
      ementa: "",
      credito: 5.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "8.8",
      status: "",
      tipo: "6",
      cargaHor: 90,
    },
    {
      codigo: "EEL630",
      nome: "Modelos Probabilísticos em Eng.",
      ementa: "",
      credito: 4.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "7.2",
      status: "",
      tipo: "6",
      cargaHor: 60,
    },
    {
      codigo: "EEL640",
      nome: "Comunicações I",
      ementa: "",
      credito: 5.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "8.9",
      status: "",
      tipo: "6",
      cargaHor: 75,
    },
    {
      codigo: "EEL660",
      nome: "Controle Linear I A",
      ementa: "",
      credito: 5.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "9.2",
      status: "",
      tipo: "6",
      cargaHor: 75,
    },
    {
      codigo: "EEL670",
      nome: "Linguagens de Programação",
      ementa: "",
      credito: 5.0,
      prof: "",
      sala: "",
      preReq: "",
      hora: {
        hora1: { dia: "", inicio: "", fim: "" },
        hora2: { dia: "", inicio: "", fim: "" },
        hora3: { dia: "", inicio: "", fim: "" },
      },
      nota: "9.8",
      status: "",
      tipo: "6",
      cargaHor: 90,
    },
  ],
};

module.exports = period6;
